### ISSUE TITLE
Problem with Authorize

### ISSUE THREAD

**Issue by encisek** [Baza207/NetatmoSwiftSDK#6]
Hi, 
I have problem with authorize user: 

My url is:
`https://api.netatmo.com/oauth2/authorize?client_id=<CLIENT-ID>&redirect_uri=<NAME URI>://auth&scope=read_camera&state=<state>
`
but inSafari i have:
"{"error":{"code":404,"message":"method not found"}}" 

You can help, what am I doing wrong?

Thanks!

@Baza207

**Comment by Baza207** [comment]
Hey @encisek 

I think that URL looks fine (assuming you've redacted the things in <>). Have you gone through [Documentation/Authentication-Setup.md](https://github.com/Baza207/NetatmoSwiftSDK/blob/master/Documentation/Authentication-Setup.md) as well as setup your app fully in the [Netatmo Developer Portal](https://dev.netatmo.com/apps)? From what other users have seen you also need to leave "Redirect URI" and "Webhook URI" blank when creating you're app on the Netatmo site.

I hope this helps. 🙂

**Comment by encisek** [comment]
@Baza207 :)
The problem was that the "_" in the URI :)
Time now I have a problem to get the house data:
```

NetatmoSecurity.getHomeData { (result) in
            switch result {
            case .success(let model):
                print(model)
            case .failure(let error):
                print(error)
            }
        }
```

`keyNotFound(CodingKeys(stringValue: "is_local", intValue: nil), Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "body", intValue: nil), CodingKeys(stringValue: "homes", intValue: nil), _JSONKey(stringValue: "Index 0", intValue: 0), CodingKeys(stringValue: "cameras", intValue: nil), _JSONKey(stringValue: "Index 0", intValue: 0)], debugDescription: "No value associated with key CodingKeys(stringValue: \"is_local\", intValue: nil) (\"is_local\").", underlyingError: nil))`

**Comment by Baza207** [comment]
Ah, glad you got authorisation fixed.

Seems like your get home data issue is similar to the one in #5. I'll have a look into it later and post once I've pushed a fix to develop so you can test. Seems like I need a more robust way of parsing the JSON, as my assumptions on Netatmo returning all fields aren't 100% sadly. 😞

**Comment by encisek** [comment]
@Baza207 
Thank you!
When are you planning to sit down on this? :)

**Comment by Baza207** [comment]
If I get a chance I'll do it tonight. 🤞

**Comment by encisek** [comment]
Cool! 👍

**Comment by Baza207** [comment]
@encisek I just pushed a fix to `develop` that you can test which makes `isLocal` optional. Let me know if you get any other warning about not returned values.

Also about your people question, yes when you get `HomeData` which has an array of `Home`s, you then get an array of people (`Person`) in each `Home`. Each `Person` has a name (`pseudo`) which is only set when the user has "saved" them. I've just added a quick helper property to `Person` called `isKnown: Bool` which basically returns `true` or `false` depending on if `pseudo` is `nil` or not.

I hope this helps. 🙂

**Comment by encisek** [comment]
Thanks @Baza207 
Should i update cocapods?

**Comment by encisek** [comment]
Thank you! @Baza207 

I just downloaded develop from:
`pod 'NetatmoSwiftSDK', :git => 'https://github.com/Baza207/NetatmoSwiftSDK', :branch => 'develop'`

But I still have the error: 
`keyNotFound(CodingKeys(stringValue: "is_local", intValue: nil), Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "body", intValue: nil), CodingKeys(stringValue: "homes", intValue: nil), _JSONKey(stringValue: "Index 0", intValue: 0), CodingKeys(stringValue: "cameras", intValue: nil), _JSONKey(stringValue: "Index 0", intValue: 0)], debugDescription: "No value associated with key CodingKeys(stringValue: \"is_local\", intValue: nil) (\"is_local\").", underlyingError: nil))`

**Comment by Baza207** [comment]
@encisek Can you check that the `isLocal` property in the `Camera` model is optional on the version you downloaded?

**Comment by encisek** [comment]
Yes, but it doesn't work, I can see a few differences, for example:

**Person** LastSeen is Int, not Date
"last_seen": 1596055468,

**event:** 
date, = time, "time": 1596217462,

**Comment by Baza207** [comment]
Hey @encisek

Hmm, that's strange that it doesn't work if it's showing as optional for that property.

Those difference are expected. I've normalised some names using [`CodingKeys`](https://github.com/Baza207/NetatmoSwiftSDK/blob/master/Source/Models/Security/Event.swift#L104) to make them more in line norms or more Swifty. Also, I'm using the [`dateDecodingStrategy`](https://github.com/Baza207/NetatmoSwiftSDK/blob/master/Source/Extensions/JSONDecoderExtensions.swift#L16) for `JSONDecoder` to automatically convert timestamps to dates.

Do you mind creating a new issue for this if it's still causing a problem. Thanks 🙂
